Update sensor.py
Hey Wouter, hope all is well. Many thanks for all your amazing work.

I noticed my sensors where broken since past 2 months (using local gateway API), I assume after upgrading one of the underlying libraries in one of the previous builds.

This was the error message in the logs:
Error while setting up openmotics platform for sensor: 'EnergySensor' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/openmotics/sensor.py", line 68, in async_setup_entry
    entities.append(OpenMoticsLocalVoltage(coordinator, index, om_sensor))
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmotics/sensor.py", line 191, in __init__
    f"energy-{device['idx']}-{self.device_class}",
              ~~~~~~^^^^^^^
TypeError: 'EnergySensor' object is not subscriptable

Changing it from dictionary to attribute access did seem to solve it for me.